package myPackage;


import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;

public class frmAddExpense extends javax.swing.JInternalFrame {
    
        private static final String JDBC_URL = "jdbc:mysql://localhost:3306/expensemanagement";
        private static final String DB_USER = "root";
        private static final String DB_PASSWORD = "880011mysqlfeni";

    
    public frmAddExpense() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        lblDate = new javax.swing.JLabel();
        lblReason = new javax.swing.JLabel();
        cboReason = new javax.swing.JComboBox<>();
        lblAmount = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtDate = new javax.swing.JTextField();

        jRadioButton1.setText("jRadioButton1");

        setClosable(true);
        setTitle("Amount:");

        lblDate.setText("Date:");

        lblReason.setText("Reason:");

        cboReason.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "transport", "entertainment", "food", "other", "" }));
        cboReason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboReasonActionPerformed(evt);
            }
        });

        lblAmount.setText("Amount:");

        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
        });

        btnClear.setText("clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReason)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboReason, 0, 159, Short.MAX_VALUE)
                    .addComponent(txtDate)
                    .addComponent(txtAmount))
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(18, 18, 18)
                .addComponent(btnClear)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReason)
                    .addComponent(cboReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAmount)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnClear))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboReasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboReasonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboReasonActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        // TODO add your handling code here:
        txtAmount.setText("");
        txtDate.setText("");
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
    String date = txtDate.getText();
    String reason = cboReason.getSelectedItem().toString();
    String amount = txtAmount.getText();

    if (date.isEmpty() || reason.isEmpty() || amount.isEmpty()) {
        JOptionPane.showMessageDialog(null, "All fields are required.");
        return; 
    }


    SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
    dateFormat.setLenient(false); 
    try {
        dateFormat.parse(date);
    } catch (ParseException ex) {
        JOptionPane.showMessageDialog(null, "Invalid date format. Please enter the date in MM/dd/yyyy format.");
        return; 
    }

        try {
        double formattedAmount = Double.parseDouble(amount);
        if (formattedAmount <= 0) {
            JOptionPane.showMessageDialog(null, "Amount must be a positive number.");
            return; 
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(null, "Invalid amount. Please enter a valid number.");
        return; 
    }
    

//    saveToFile(date, reason, amount);


    String formattedDate = null; 
    try {
        SimpleDateFormat inputFormat = new SimpleDateFormat("MM/dd/yyyy");
        SimpleDateFormat outputFormat = new SimpleDateFormat("yyyy-MM-dd");
        formattedDate = outputFormat.format(inputFormat.parse(date));
    } catch (ParseException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Invalid date format. Please enter the date in MM/dd/yyyy format.");
        return; 
    }

    // Save to database
    saveToDatabase(formattedDate, reason, amount);
            
      

    }//GEN-LAST:event_btnSaveMouseClicked
     private void saveToFile(String date, String reason, String amount) {
    String content = date + "," + reason + "," + amount;

    try {
        FileWriter writer = new FileWriter("C:\\Users\\hp\\OneDrive\\Desktop\\Java_File\\dailyExpenses.txt", true);
        BufferedWriter bufferedWriter = new BufferedWriter(writer);
        bufferedWriter.write(content);
        bufferedWriter.newLine();
        bufferedWriter.close();

        JOptionPane.showMessageDialog(null, "Daily expense saved successfully!");
    } catch (IOException ex) {
        ex.printStackTrace();
        java.util.logging.Logger.getLogger(frmAddExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
}
 private void saveToDatabase(String date, String reason, String amount) {
        try (Connection connection = DriverManager.getConnection(JDBC_URL, DB_USER, DB_PASSWORD)) {
            int userId = UserManager.getCurrentUserId(); 
            String sql = "INSERT INTO expense_info(user_id, date, reason, amount) VALUES (?, ?, ?, ?)";
            try (PreparedStatement statement = connection.prepareStatement(sql)) {
                statement.setInt(1, userId); 
                statement.setString(2, date);
                statement.setString(3, reason);
                statement.setString(4, amount);
                int rowsInserted = statement.executeUpdate();
                if (rowsInserted > 0) {
                    JOptionPane.showMessageDialog(null, "Daily expense saved successfully!");
                }
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "An error occurred while saving to database.");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cboReason;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblReason;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtDate;
    // End of variables declaration//GEN-END:variables
}
