package myPackage;


import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.sql.ResultSet;


public class frmShowAllExpense extends javax.swing.JInternalFrame {
    
     private boolean useFile = false; 


        private static final String JDBC_URL = "jdbc:mysql://localhost:3306/expensemanagement";
        private static final String DB_USER = "root";
        private static final String DB_PASSWORD = "880011mysqlfeni";
      
       
        
   
    public frmShowAllExpense() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnShowAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExpenseList = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Show Expense");

        btnShowAll.setText("Show All Expense");
        btnShowAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnShowAllMouseClicked(evt);
            }
        });
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        tblExpenseList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "Reason", "Amount"
            }
        ));
        jScrollPane1.setViewportView(tblExpenseList);

        jButton1.setText("Delete");
        jButton1.setMaximumSize(new java.awt.Dimension(82, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(82, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort By Date", "Sort By Amount" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnShowAll)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnShowAll)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
          
// TODO add your handling code here:
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void btnShowAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowAllMouseClicked
        // TODO add your handling code here:
        
       if (useFile) {
            showAllExpensesFromFile();
        } else {
            showAllExpensesFromDatabase();
        }
         
    }//GEN-LAST:event_btnShowAllMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int userId = UserManager.getCurrentUserId();
    ExpenseDeleter expenseDeleter = new ExpenseDeleter();
    expenseDeleter.deleteExpense(tblExpenseList, userId);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
      String selectedOption = (String) jComboBox1.getSelectedItem();
    
    // Determine which sorting method to call based on the selected option
   if (selectedOption.equalsIgnoreCase("Sort By Date")) {
    ExpenseSorter.sortByDate(tblExpenseList);
} else if (selectedOption.equalsIgnoreCase("Sort By Amount")) {
    ExpenseSorter.sortByAmount(tblExpenseList);
}

       
       // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         ExpenseEditor.editExpense(tblExpenseList);
    }//GEN-LAST:event_jButton2ActionPerformed
private void showAllExpensesFromDatabase() {
    try (Connection connection = DriverManager.getConnection(JDBC_URL, DB_USER, DB_PASSWORD)) {
        int userId = UserManager.getCurrentUserId(); // Assuming UserManager provides a method to get the current user ID
        String sql = "SELECT expense_id, date, reason, amount FROM expense_info WHERE user_id = ?";
        try (PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setInt(1, userId);
            try (ResultSet resultSet = statement.executeQuery()) {
                DefaultTableModel model = new DefaultTableModel();
                model.addColumn("Expense ID");
                model.addColumn("Expense Date");
                model.addColumn("Expense Reason");
                model.addColumn("Expense Amount");
               
                SimpleDateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
                while (resultSet.next()) {
                    int expenseId = resultSet.getInt("expense_id");
                    String date = dateFormat.format(resultSet.getDate("date"));
                    String reason = resultSet.getString("reason");
                    String amount = resultSet.getString("amount");
                    model.addRow(new Object[]{expenseId, date, reason, amount});
                }
                tblExpenseList.setModel(model);
                tblExpenseList.getColumnModel().removeColumn(tblExpenseList.getColumnModel().getColumn(0));
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace(); 
    }
}

 private void showAllExpensesFromFile() {
 try {
            FileReader reader = new FileReader("C:\\Users\\hp\\OneDrive\\Desktop\\Java_File\\dailyExpenses.txt");
            
            BufferedReader bufferedReader = new BufferedReader (reader);
            
            String[][] expenses = new String[10][3];
            int rowCounter = 0;
            String line ="";
            
            while ((line = bufferedReader.readLine()) != null){
                    String[] singleLine = line.split(",");
                    expenses[rowCounter][0] = singleLine[0];
                    expenses[rowCounter][1] = singleLine[1];
                    expenses[rowCounter][2] = singleLine[2];
                    
                    rowCounter++;
            }
        
            String[] columns = new String[]{
                "Expense Date","Expense Reason","Expense Amount"};
            final Class[] columnClass = new Class[]{
            String.class,String.class,String.class
                    
            };
            
            DefaultTableModel model = new DefaultTableModel(expenses,columns){
                public boolean isCellEditable(int row,int column){
                    return false;
                }
                public Class<?> getColumnClass(int columnIndex){
                    return columnClass[columnIndex];
                }
            };
            tblExpenseList.setModel(model);
             
        }catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSearchExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(frmSearchExpense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowAll;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblExpenseList;
    // End of variables declaration//GEN-END:variables
}
